# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks

color_good="#88b090"
color_warn="#ccdc90"
color_crit="#e89393"
color_info="#FCE94F"

# Global properties
separator=true
separator_block_width=12

[ethernet]
command=/home/ttrreevvoorr/scripts/i3status/ethernet.sh
interval=10
color=#00FF00

[disk]
command=/home/ttrreevvoorr/scripts/i3status/disk.sh
interval=30
label= 


[cpu_load]
command=/home/ttrreevvoorr/scripts/i3status/cpu_load_avg.sh
interval=5
label= 

[cpu_temp]
command=/home/ttrreevvoorr/scripts/i3status/cpu_temp.sh
interval=5
label= 

[memory]
command=/home/ttrreevvoorr/scripts/i3status/memory.sh
interval=10
label=MEM 

[volume]
command=/home/ttrreevvoorr/scripts/i3status/volume.sh
interval=1
label=
color=#00FFFF

[weather]
command=/home/ttrreevvoorr/scripts/i3status/weather.sh
interval=360

[time]
command=date '+%Y-%m-%d %H:%M:%S'
interval=1
